### PR TITLE
Bump nix version number

### PR DESCRIPTION
**Pull request by Sineaggi**
From nix 0.8.0 to 0.9.0.

### CODE REVIEW

**Comment by vishvananda** [comment]
thank you for this patch. You'll need to sign the oracle cla before I can merge it.

**Comment by Sineaggi** [comment]
@vishvananda signed

**Comment by Sineaggi** [comment]
Any updates?

**Comment by vishvananda** [comment]
Hi sorry this has taken so long. I was waiting for the acknowledgement of the signed cla to show up on this page: http://www.oracle.com/technetwork/community/oca-486395.html

I haven't seen it yet. Did you receive a response to your submission?

**Pull request merged**
